logging:
  # Cấu hình file log
  log_file_path: "logs/application.log"
  log_level: "INFO"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  
  # Cấu hình format
  format:
    file: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
    console: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
    date_format: "%Y-%m-%d %H:%M:%S"
  
  # Cấu hình màu sắc cho console
  colors:
    DEBUG: "cyan"
    INFO: "green"
    WARNING: "yellow"
    ERROR: "red"
    CRITICAL: "bold_red"
  
  # Cấu hình các logger cụ thể
  loggers:
    root:
      level: "INFO"
      handlers: ["console", "file"]
    
    # Logger cho các module cụ thể
    sensors:
      level: "DEBUG"
      handlers: ["console", "file"]
      propagate: false
    
    mqtt:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
    
    processing:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false
  
  # Cấu hình handlers
  handlers:
    console:
      class: "colorlog.StreamHandler"
      level: "DEBUG"
      formatter: "console"
      stream: "ext://sys.stdout"
    
    file:
      class: "logging.handlers.RotatingFileHandler"
      level: "DEBUG"
      formatter: "file"
      filename: "logs/application.log"
      maxBytes: 10485760
      backupCount: 5
      encoding: "utf-8"
  
  # Cấu hình formatters
  formatters:
    console:
      format: "%(log_color)s%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    
    file:
      format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S" 